<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Validator;

class Text extends Authenticatable
{
    protected $table = "text";

    public function addNew($data)
    {
        
        $lid = $data['lid'];

        for($i=0;$i<count($lid);$i++)
        {       
            $allData = [

            'city_search'         => $data['city_search'][$i],
            'city_locate'         => $data['city_locate'][$i],
            'city_address'        => $data['city_address'][$i],
            'land_mark'           => $data['land_mark'][$i],
            'city_save'           => $data['city_save'][$i],
            'search'              => $data['search'][$i],
            'trend_in'            => $data['trend_in'][$i],
            'exit_app'            => $data['exit_app'][$i],
            'exit_app_desc'       => $data['exit_app_desc'][$i],
            'exit_app_confirm'    => $data['exit_app_confirm'][$i],
            'previous_order'      => $data['previous_order'][$i],
            'sort_by'             => $data['sort_by'][$i],
            'rating'              => $data['rating'][$i],
            'nearest'             => $data['nearest'][$i],
            'new_arrival'         => $data['new_arrival'][$i],
            'km'                  => $data['km'][$i],
            'per_person'         => $data['per_person'][$i],
            'search_title'        => $data['search_title'][$i],
            'search_res'          => $data['search_res'][$i],
            'trend_search'        => $data['trend_search'][$i],
            'menu_title'          => $data['menu_title'][$i],
            'view_info'           => $data['view_info'][$i],
            'delivery_time'       => $data['delivery_time'][$i],
            'close_time'          => $data['close_time'][$i],
            'store_close'         => $data['store_close'][$i],
            'all'                 => $data['all'][$i],
            'select_size'         => $data['select_size'][$i],
            'req_addon'           => $data['req_addon'][$i],
            'add_cart'            => $data['add_cart'][$i],
            'add_cart_msg'        => $data['add_cart_msg'][$i],
            'remove_cart_msg'     => $data['remove_cart_msg'][$i],
            'rating_review'       => $data['rating_review'][$i],
            'cart_title'          => $data['cart_title'][$i],
            'cart_price'          => $data['cart_price'][$i],
            'cart_qty'            => $data['cart_qty'][$i],
            'have_discount'       => $data['have_discount'][$i],
            'apply_here'          => $data['apply_here'][$i],
            'sub_total'           => $data['sub_total'][$i],
            'd_charges'           => $data['d_charges'][$i],
            'discount'            => $data['discount'][$i],
            'total_payable'       => $data['total_payable'][$i],
            'checkout'            => $data['checkout'][$i],
            'empty'               => $data['empty'][$i],
            'start_shopping'      => $data['start_shopping'][$i],
            'select_offer'        => $data['select_offer'][$i],
            'apply'               => $data['apply'][$i],
            'no_offer'            => $data['no_offer'][$i],
            'remove'              => $data['remove'][$i],
            'offer_applied'       => $data['offer_applied'][$i],
            'cashback_msg'        => $data['cashback_msg'][$i],
            'login_title'         => $data['login_title'][$i],
            'login_email'         => $data['login_email'][$i],
            'login_password'      => $data['login_password'][$i],
            'login_button'        => $data['login_button'][$i],
            'forgot_pass'         => $data['forgot_pass'][$i],
            'dont_have'           => $data['dont_have'][$i],
            'signup_now'          => $data['signup_now'][$i],
            'login_validation'    => $data['login_validation'][$i],
            'login_error'         => $data['login_error'][$i],
            'signup_title'        => $data['signup_title'][$i],
            'signup_desc'         => $data['signup_desc'][$i],
            'signup_name'         => $data['signup_name'][$i],
            'signup_phone'        => $data['signup_phone'][$i],
            'signup_email'        => $data['signup_email'][$i],
            'rcode'               => $data['rcode'][$i],
            'signup_password'     => $data['signup_password'][$i],
            'signup_btn'          => $data['signup_btn'][$i],
            'signup_error'        => $data['signup_error'][$i],
            'forgot_title'        => $data['forgot_title'][$i],
            'forgot_text'         => $data['forgot_text'][$i],
            'enter_email'         => $data['enter_email'][$i],
            'reset'               => $data['reset'][$i],
            'verify_email'        => $data['verify_email'][$i],
            'enter_otp'           => $data['enter_otp'][$i],
            'verify'              => $data['verify'][$i],
            'new_pass'            => $data['new_pass'][$i],
            'new_password'        => $data['new_password'][$i],
            'confirm_password'    => $data['confirm_password'][$i],
            'update_pass'         => $data['update_pass'][$i],
            'otp_sent_msg'        => $data['otp_sent_msg'][$i],
            'otp_validation'      => $data['otp_validation'][$i],
            'new_pass_validation'  => $data['new_pass_validation'][$i],
            'confirm_pass_validation' => $data['confirm_pass_validation'][$i],
            'password_update_msg'     => $data['password_update_msg'][$i],
            'order_type'          => $data['order_type'][$i],
            'delivery'            => $data['delivery'][$i],
            'pickup'              => $data['pickup'][$i],
            'order_date_time'     => $data['order_date_time'][$i],
            'deliver_today'       => $data['deliver_today'][$i],
            'deliver_later'       => $data['deliver_later'][$i],
            'select_date'         => $data['select_date'][$i],
            'select_time'         => $data['select_time'][$i],
            'select'              => $data['select'][$i],
            'persoanl_info'       => $data['persoanl_info'][$i],
            'name'                => $data['name'][$i],
            'phone'               => $data['phone'][$i],
            'address'             => $data['address'][$i],
            'landmark'            => $data['landmark'][$i],
            'comment'             => $data['comment'][$i],
            'payment_method'      => $data['payment_method'][$i],
            'cod'                 => $data['cod'][$i],
            'stripe'              => $data['stripe'][$i],
            'razor'               => $data['razor'][$i],
            'stripe_title'        => $data['stripe_title'][$i],
            'card_no'             => $data['card_no'][$i],
            'exp_month'           => $data['exp_month'][$i],
            'exp_year'            => $data['exp_year'][$i],
            'cvv'                 => $data['cvv'][$i],
            'book_now'            => $data['book_now'][$i],
            'stripe_validation'   => $data['stripe_validation'][$i],
            'stripe_config'       => $data['stripe_config'][$i],
            'card_no_validation'  => $data['card_no_validation'][$i],
            'apt_success'         => $data['apt_success'][$i],
            'ref_no'              => $data['ref_no'][$i],
            'total_amount'        => $data['total_amount'][$i],
            'go_back'             => $data['go_back'][$i],
            'address_add'         => $data['address_add'][$i],
            'address_msg'         => $data['address_msg'][$i],
            'ecash_desc'          => $data['ecash_desc'][$i],
            'ecash'                 => $data['ecash'][$i],
            'use_ecash'             => $data['use_ecash'][$i],
            'no_running_order'      => $data['no_running_order'][$i],
            'on_going_order'        => $data['on_going_order'][$i],
            'order_from'            => $data['order_from'][$i],
            'order_placed_text'     => $data['order_placed_text'][$i],
            'order_confirmed_text'  => $data['order_confirmed_text'][$i],
            'delivery_assign_text'  => $data['delivery_assign_text'][$i],
            'order_on_way'          => $data['order_on_way'][$i],
            'order_cancel_text'     => $data['order_cancel_text'][$i],
            'order_no'              => $data['order_no'][$i],
            'order_detail'          => $data['order_detail'][$i],
            'call'                  => $data['call'][$i],
            'welcome'               => $data['welcome'][$i],
            'ref_code'              => $data['ref_code'][$i],
            'ref_code_desc'         => $data['ref_code_desc'][$i],
            'account_title'             => $data['account_title'][$i],
            'my'                        => $data['my'][$i],
            'lang_setting'              => $data['lang_setting'][$i],
            'change_location'           => $data['change_location'][$i],
            'back_home'                 => $data['back_home'][$i],
            'logout'                    => $data['logout'][$i],
            'order_date'                => $data['order_date'][$i],
            'status'                    => $data['status'][$i],
            'item'                      => $data['item'][$i],
            'qty'                       => $data['qty'][$i],
            'price'                     => $data['price'][$i],
            'no_order'                  => $data['no_order'][$i],
            'cancel_order'              => $data['cancel_order'][$i],
            'cancel_order_confirm'         => $data['cancel_order_confirm'][$i],
            'cancel_order_confirm_desc'    => $data['cancel_order_confirm_desc'][$i],
            'rating_title'                 => $data['rating_title'][$i],
            'rating_des'                   => $data['rating_des'][$i],
            'submit_btn'                   => $data['submit_btn'][$i],
            'menu_welcome'                 => $data['menu_welcome'][$i],
            'menu_home'                    => $data['menu_home'][$i],
            'menu_my'                      => $data['menu_my'][$i],
            'menu_my_account'              => $data['menu_my_account'][$i],
            'menu_lang'                    => $data['menu_lang'][$i],
            'menu_location'                => $data['menu_location'][$i],
            'running_order'                => $data['running_order'][$i],
            'menu_about'                   => $data['menu_about'][$i],
            'menu_faq'                     => $data['menu_faq'][$i],
            'menu_contact'                 => $data['menu_contact'][$i],
            'lang_title'                   => $data['lang_title'][$i],
            'update_lang'                  => $data['update_lang'][$i],
            'd_login_phone'                => $data['d_login_phone'][$i],
            'd_home_title'                 => $data['d_home_title'][$i],
            'd_active'                     => $data['d_active'][$i],
            'd_offline'                    => $data['d_offline'][$i],
            'd_no_order'                   => $data['d_no_order'][$i],
            'd_order_id'                   => $data['d_order_id'][$i],
            'd_user'                       => $data['d_user'][$i],
            'd_phone'                      => $data['d_phone'][$i],
            'd_address'                    => $data['d_address'][$i],
            'd_view_detail'                => $data['d_view_detail'][$i],
            'd_accept'                     => $data['d_accept'][$i],
            'd_show_dir'                   => $data['d_show_dir'][$i],
            'd_order_item'                 => $data['d_order_item'][$i],
            'd_other_info'                 => $data['d_other_info'][$i],
            'd_total_amount'               => $data['d_total_amount'][$i],
            'd_payment_method'             => $data['d_payment_method'][$i],
            'd_cod'                        => $data['d_cod'][$i],
            'd_online'                     => $data['d_online'][$i],
            'd_ecash_paid'                 => $data['d_ecash_paid'][$i],
            'd_paid_ecash'                 => $data['d_paid_ecash'][$i],
            'd_total_pay'                  => $data['d_total_pay'][$i],
            'd_start_ride'                 => $data['d_start_ride'][$i],
            'd_complete_ride'              => $data['d_complete_ride'][$i],
            'd_confirm'                    => $data['d_confirm'][$i],
            'd_order_start'                => $data['d_order_start'][$i],
            'd_order_delivered'            => $data['d_order_delivered'][$i],
            'd_account_title'              => $data['d_account_title'][$i],
            'd_my_order'                   => $data['d_my_order'][$i],
            'd_change_pass'                => $data['d_change_pass'][$i],
            's_dont_have'                  => $data['s_dont_have'][$i],
            's_signup_now'                 => $data['s_signup_now'][$i],
            's_signup_title'               => $data['s_signup_title'][$i],
            's_signup_desc'                => $data['s_signup_desc'][$i],
            's_signup_name'                => $data['s_signup_name'][$i],
            's_signup_phone'               => $data['s_signup_phone'][$i],
            's_signup_address'             => $data['s_signup_address'][$i],
            's_signup_pass'                => $data['s_signup_pass'][$i],
            's_submit'                     => $data['s_submit'][$i],
            's_order_overview'             => $data['s_order_overview'][$i],
            's_total_order'                => $data['s_total_order'][$i],
            's_complete_order'             => $data['s_complete_order'][$i],
            's_new_order'                  => $data['s_new_order'][$i],
            's_canceled_order'             => $data['s_canceled_order'][$i],
            's_delivery'                   => $data['s_delivery'][$i],
            's_pickup'                     => $data['s_pickup'][$i],
            's_new_order_status'           => $data['s_new_order_status'][$i],
            's_confirm_order_status'       => $data['s_confirm_order_status'][$i],
            's_delivery_assign_status'     => $data['s_delivery_assign_status'][$i],
            's_on_way_status'              => $data['s_on_way_status'][$i],
            's_ecash_used'                 => $data['s_ecash_used'][$i],
            's_cancel_order'               => $data['s_cancel_order'][$i],
            's_confirm_order'              => $data['s_confirm_order'][$i],
            's_assign_delivery'            => $data['s_assign_delivery'][$i],
            's_select_delivery_boy'        => $data['s_select_delivery_boy'][$i],
            's_assign_btn'                 => $data['s_assign_btn'][$i],
            's_order_cancel_msg'           => $data['s_order_cancel_msg'][$i],
            's_order_status_msg'           => $data['s_order_status_msg'][$i],
            's_update_account'             => $data['s_update_account'][$i],
            's_delivery_charges'           => $data['s_delivery_charges'][$i],
            's_enter_km_fix'               => $data['s_enter_km_fix'][$i],
            's_enter_amount_fix'           => $data['s_enter_amount_fix'][$i],
            's_amount_after'               => $data['s_amount_after'][$i],
            's_max_delivery'               => $data['s_max_delivery'][$i],
            's_store_open_close'           => $data['s_store_open_close'][$i],
            's_store_open'                 => $data['s_store_open'][$i],
            's_email_error'                => $data['s_email_error'][$i],
            's_setting_update'             => $data['s_setting_update'][$i],
            's_menu_item'                  => $data['s_menu_item'][$i],
            's_all_item'                   => $data['s_all_item'][$i],
            's_edit'                       => $data['s_edit'][$i],
            's_small_price'                => $data['s_small_price'][$i],
            's_medium_price'               => $data['s_medium_price'][$i],
            's_full_price'                 => $data['s_full_price'][$i],
            's_signup_msg'                 => $data['s_signup_msg'][$i],
            'close'                        => $data['close'][$i],
            'time_period'                  => $data['time_period'][$i],
            'pay_with_cash'                => $data['pay_with_cash'][$i],
            'bank_transfer'                => $data['bank_transfer'][$i],
            'term'                         => $data['term'][$i],
            'term_text'                    => $data['term_text'][$i],
            'my_plan'                      => $data['my_plan'][$i],
            'my_plan_text'                 => $data['my_plan_text'][$i],
            'valid_till'                   => $data['valid_till'][$i],
            'change_plan'                  => $data['change_plan'][$i],
            'select_plan'                  => $data['select_plan'][$i],
            'notes_bank'                   => $data['notes_bank'][$i],
            'my_earn'                      => $data['my_earn'][$i],
            'my_earn_text'                 => $data['my_earn_text'][$i],
            'total_complete_order'         => $data['total_complete_order'][$i],
            'total_earn'                   => $data['total_earn'][$i],
            'from_month'                   => $data['from_month'][$i],
            'eta'                          => $data['eta'][$i],
            'reco'                         => $data['reco'][$i],
            'out_stock'                    => $data['out_stock'][$i],
            'out_stock_msg'                => $data['out_stock_msg'][$i],
            'out_stock_msg_checkout'       => $data['out_stock_msg_checkout'][$i],
            'login_btn'                    => $data['login_btn'][$i],
            'sign_btn'                     => $data['sign_btn'][$i],
            'delivery_title'               => $data['delivery_title'][$i],
            'dinein_title'                 => $data['dinein_title'][$i],
            'location_title'               => $data['location_title'][$i],
            'direction'                    => $data['direction'][$i],
            'contact_no'                   => $data['contact_no'][$i],
            'call_now'                     => $data['call_now'][$i],
            'timing'                       => $data['timing'][$i],
            'avg_per'                      => $data['avg_per'][$i],
            'view_menu'                    => $data['view_menu'][$i],
            'access_page'                  => $data['access_page'][$i],
            'pay_paypal'                   => $data['pay_paypal'][$i],
            'pay_paystack'                 => $data['pay_paystack'][$i],
            'paypal_fail'                  => $data['paypal_fail'][$i],
            'text_paypal_wrong'            => $data['text_paypal_wrong'][$i],
            'd_charge_msg'                 => $data['d_charge_msg'][$i],
            'select_location'              => $data['select_location'][$i],
            'clear'                        => $data['clear'][$i],
            'fast_delivery'                => $data['fast_delivery'][$i],
            'choose_category'              => $data['choose_category'][$i],
            'view_all'                     => $data['view_all'][$i],
            'store_around'                 => $data['store_around'][$i],
            'showing_category'             => $data['showing_category'][$i],
            'filter_by'                    => $data['filter_by'][$i],
            'footer_cart'                  => $data['footer_cart'][$i],
            'footer_profile'               => $data['footer_profile'][$i],
            'your_profile'                 => $data['your_profile'][$i],
            'menu_desc'                    => $data['menu_desc'][$i],
            'conti'                        => $data['conti'][$i],
            'view_account'                 => $data['view_account'][$i],
            'search_res'                   => $data['search_res'][$i],
            'all_store_deliver'            => $data['all_store_deliver'][$i],
            'recent_search_query'          => $data['recent_search_query'][$i],
            'veg'                          => $data['veg'][$i],
            'nonveg'                       => $data['nonveg'][$i],
            'add'                          => $data['add'][$i],
            'cooking_notes'                => $data['cooking_notes'][$i],
            'write_note'                   => $data['write_note'][$i],
            'country'                      => $data['country'][$i],
            'verify_your_email'            => $data['verify_your_email'][$i],
            'verify_your_phone'            => $data['verify_your_phone'][$i],
            'verify_code_sent'             => $data['verify_code_sent'][$i],
            'i_agree'                      => $data['i_agree'][$i],
            'terms'                        => $data['terms'][$i],
            'add_tip'                      => $data['add_tip'][$i],
            'tip_added'                    => $data['tip_added'][$i],
            'address_payment'              => $data['address_payment'][$i],
            'select_delivery_address'      => $data['select_delivery_address'][$i],
            'want_new_address'             => $data['want_new_address'][$i],
            'select_tip'                   => $data['select_tip'][$i],
            'fw'                            => $data['fw'][$i],
            'start_using'                   => $data['start_using'][$i],
            'ecash_use_desc'                => $data['ecash_use_desc'][$i],
            'w_chat'                        => $data['w_chat'][$i],
            'view_less'                     => $data['view_less'][$i],
            'get_started'                   => $data['get_started'][$i],
            'email_us'                      => $data['email_us'][$i],
            'call_us'                       => $data['call_us'][$i],
            'send_msg'                      => $data['send_msg'][$i],
            'any_query'                     => $data['any_query'][$i],
            'your_msg'                      => $data['your_msg'][$i],
            'decline'                       => $data['decline'][$i],
            'you_earn'                      => $data['you_earn'][$i],
            'drop_off'                      => $data['drop_off'][$i],
            'pickup'                        => $data['pickup'][$i],
            'hotspot'                       => $data['hotspot'][$i],
            'edit'                          => $data['edit'][$i],
            'delete'                        => $data['delete'][$i],
            'add_new'                       => $data['add_new'][$i],
            'select_category'               => $data['select_category'][$i],
            'item_name'                     => $data['item_name'][$i],
            'description'                   => $data['description'][$i],
            'item_type'                     => $data['item_type'][$i],
            'both'                          => $data['both'][$i],
            'sort_order'                    => $data['sort_order'][$i],
            'upload_img'                    => $data['upload_img'][$i],
            'new_cate_name'                 => $data['new_cate_name'][$i],
            
            ];

            Text::where('lang_id',$lid[$i])->delete();

            $add            = new Text;
            $add->lang_id   = $lid[$i]; 
            $add->s_data    = serialize($allData); 
            $add->save();  
        }
    }

    public function getSData($i,$index)
    {
    	$res = Text::where('lang_id',$i)->first();

    	if(isset($res->id))
    	{
    		$sdata = unserialize($res->s_data);

    		return isset($sdata[$index]) ? $sdata[$index] : null;
    	}
    	else
    	{
    		return null;
    	}
    }

    public function getAppData($id)
    {
        $res = Text::where('lang_id',$id)->first();
   
        return unserialize($res->s_data);
    }
}
